# Generated by Django 3.1 on 2020-08-11 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=99)),
                ('address', models.CharField(max_length=99)),
                ('instagram', models.URLField()),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=99)),
                ('last_name', models.CharField(max_length=99)),
                ('Bio', models.CharField(max_length=99)),
                ('about_me', models.CharField(max_length=500)),
                ('resume', models.URLField()),
                ('profile_image1', models.ImageField(upload_to='media')),
                ('profile_image2', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=99)),
                ('project_category', models.CharField(max_length=99)),
                ('project_link', models.URLField()),
                ('project_scrnshot', models.ImageField(upload_to='media')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 11, 11, 22, 5, 13047), verbose_name='default date time')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=99)),
                ('skill_percentage', models.IntegerField(max_length=99)),
            ],
        ),
    ]
